/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lattig.csvtodb;

import javax.swing.*;
import java.awt.*;

import static javax.swing.GroupLayout.Alignment.*;
import static javax.swing.GroupLayout.DEFAULT_SIZE;
import static javax.swing.GroupLayout.PREFERRED_SIZE;
import static javax.swing.LayoutStyle.ComponentPlacement.RELATED;

/**
 * @author Nate
 */
public class MainMenuView extends JFrame {

    /**
     * Creates new form MainMenuView
     *
     * @param menuCtrl
     */
    private MainMenuCtrl menuCtrl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton closeButton;
    private JLabel csvFileLabel;
    private JButton databaseButton;
    private JPanel jPanel1;
    private JSeparator jSeparator1;
    private JButton loadButton;
    private JLabel outputLabel;
    private JButton selectCsvButton;
    private JButton selectOutputButton;
    private JLabel titleLabel;

    public MainMenuView() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.menuCtrl = new MainMenuCtrl(this);
        jPanel1 = new JPanel();
        titleLabel = new JLabel();
        setSelectCsvButton(new JButton());
        setCsvFileLabel(new JLabel());
        setSelectOutputButton(new JButton());
        setOutputLabel(new JLabel());
        setCloseButton(new JButton());
        setLoadButton(new JButton());
        setDatabaseButton(new JButton());
        jSeparator1 = new JSeparator();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(500, 500));

        titleLabel.setFont(new Font("Dialog", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setText("CSV To DB");

        selectCsvButton.setText("Select CSV File");
        selectCsvButton.setPreferredSize(new Dimension(100, 25));
        selectCsvButton.addActionListener(e -> menuCtrl.selectCsvButtonActionPerformed());


        csvFileLabel.setText("CSV File Path");

        selectOutputButton.setText("Select Output Directory");
        selectOutputButton.setPreferredSize(new Dimension(100, 25));
        selectOutputButton.addActionListener(e -> menuCtrl.selectOutputButtonActionPerformed());

        outputLabel.setText("Directory Path");

        closeButton.setText("Close");
        closeButton.addActionListener(evt -> menuCtrl.closeButtonActionPerformed());

        loadButton.setText("Load File");
        loadButton.setPreferredSize(new Dimension(100, 25));
        loadButton.addActionListener(e -> menuCtrl.loadButtonActionPerformed());

        databaseButton.setText("View Database Contents");
        databaseButton.addActionListener(e -> menuCtrl.databaseButtonActionPerformed());

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(LEADING)
                        .addComponent(titleLabel, TRAILING, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(TRAILING)
                                        .addComponent(jSeparator1)
                                        .addComponent(getCsvFileLabel(), LEADING, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(getOutputLabel(), LEADING, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(getDatabaseButton())
                                                .addPreferredGap(RELATED, 236, Short.MAX_VALUE)
                                                .addComponent(getCloseButton()))
                                        .addGroup(LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(TRAILING)
                                                        .addComponent(getSelectOutputButton(), LEADING, PREFERRED_SIZE, 150, PREFERRED_SIZE)
                                                        .addComponent(getLoadButton(), LEADING, PREFERRED_SIZE, 151, PREFERRED_SIZE)
                                                        .addComponent(getSelectCsvButton(), LEADING, PREFERRED_SIZE, 150, PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(titleLabel, PREFERRED_SIZE, 46, PREFERRED_SIZE)
                                .addPreferredGap(RELATED)
                                .addComponent(jSeparator1, PREFERRED_SIZE, 10, PREFERRED_SIZE)
                                .addPreferredGap(RELATED, 87, Short.MAX_VALUE)
                                .addComponent(getSelectCsvButton(), PREFERRED_SIZE, DEFAULT_SIZE, PREFERRED_SIZE)
                                .addPreferredGap(RELATED)
                                .addComponent(getCsvFileLabel(), PREFERRED_SIZE, 25, PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getSelectOutputButton(), PREFERRED_SIZE, DEFAULT_SIZE, PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getOutputLabel(), PREFERRED_SIZE, 23, PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getLoadButton(), PREFERRED_SIZE, DEFAULT_SIZE, PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(BASELINE)
                                        .addComponent(getCloseButton())
                                        .addComponent(getDatabaseButton()))
                                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(LEADING)
                        .addGroup(TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );


        pack();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    //************** GETTERS & SETTERS SECTION **************


    public JButton getCloseButton() {
        return closeButton;
    }

    public void setCloseButton(JButton closeButton) {
        this.closeButton = closeButton;
    }

    public JLabel getCsvFileLabel() {
        return csvFileLabel;
    }

    public void setCsvFileLabel(JLabel csvFileLabel) {
        this.csvFileLabel = csvFileLabel;
    }

    public JButton getDatabaseButton() {
        return databaseButton;
    }

    public void setDatabaseButton(JButton databaseButton) {
        this.databaseButton = databaseButton;
    }

    public JButton getLoadButton() {
        return loadButton;
    }

    public void setLoadButton(JButton loadButton) {
        this.loadButton = loadButton;
    }

    public JLabel getOutputLabel() {
        return outputLabel;
    }

    public void setOutputLabel(JLabel outputLabel) {
        this.outputLabel = outputLabel;
    }

    public JButton getSelectCsvButton() {
        return selectCsvButton;
    }

    public void setSelectCsvButton(JButton selectCsvButton) {
        this.selectCsvButton = selectCsvButton;
    }

    public JButton getSelectOutputButton() {
        return selectOutputButton;
    }

    public void setSelectOutputButton(JButton selectOutputButton) {
        this.selectOutputButton = selectOutputButton;
    }

}
